apiVersion: v1
kind: Secret
metadata:
  name: keyinfo
  namespace: cfip
type: Opaque
data:
  cloudflareKey: <BASE64 ENCODED CLOUD_FLARE_KEY>
  pushoverUserToken: <BASE64 ENCODED PUSHOVER_USER_TOKEN>
  pushoverAppToken: <BASE64 ENCODED PUSHOVER_APP_TOKEN>
